services:
  db:
    image: mysql:8.0.33-oracle
    container_name: mysql
    ports: 
      - '3307:3306'
    volumes: 
      - dbdata:/var/lib/mysql
      - ./scripts/database/:/docker-entrypoint-initdb.d/
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=Admin@123
      - MYSQL_DATABASE=manage_apartment

  backend:
    build:
      context: backend/
    container_name: backend
    ports: 
      - '8081:8080'
    restart: unless-stopped
    depends_on:
      - db

  frontend:
    container_name: frontend
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
    ports:
      - "3000:80"
    volumes:
      - ./frontend/.nginx/nginx.conf:/etc/nginx/nginx.conf

volumes:
  dbdata:
